### ISSUE TITLE
Access To Data

### ISSUE THREAD

**Issue by anthonyromyn** [conpdatasets/CHBMP#16]
Hey CHBMP team,

I'm trying to access the data through datalad but it isn't working for me. Am I doing something wrong? 

For example,
`datalad get /cloned-CHBMP/BIDS_dataset/sub-CBM00001/ses-V01/eeg/sub-CBM00001_ses-V01_task-protmap_channels.tsv`

Thanks!
Anthony

**Comment by cmadjar** [comment]
Hi @anthonyromyn,

Sorry for the delay in getting back to you. In order to access the CHBMP dataset, you need to request an account on https://chbmp-open.loris.ca/. Once you have the credentials, you will need to use them in order to download the dataset via DataLad.

Let me know if you need more explanation on how to download the data once you have the account.

Best,

**Comment by anthonyromyn** [comment]
Awesome, thank you!
